# Generated by Django 3.1.7 on 2021-03-15 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LightLabImage',
            fields=[
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='light_lab_images/')),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
