# Generated by Django 3.1.7 on 2021-03-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0002_remove_gallery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slugid',
            field=models.SlugField(blank=True, editable=False, max_length=16),
        ),
    ]
