# Generated by Django 3.1.7 on 2021-03-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0003_auto_20210326_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightlabimage',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lightlabimage',
            name='meta_data',
            field=models.TextField(blank=True),
        ),
    ]
