# Generated by Django 3.1.7 on 2021-03-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0004_auto_20210326_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slugid',
            field=models.SlugField(editable=False, max_length=16, unique=True),
        ),
    ]
