# Generated by Django 3.1.7 on 2021-03-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0005_auto_20210326_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='meta_data',
            field=models.TextField(blank=True),
        ),
    ]
