from django.urls import path,include

from . import views
urlpatterns = [
    path('light_editor/', views.LightCode.as_view(), name='lightcode'),
    path('gallery/add/', views.AddImage.as_view(), name='addimage'),
    path('auto_gen/presets/<str:image_id>/<str:return_type>/', views.AutoGenerated.as_view(), name='auto_gen'),
    path('light_editor/<str:slugid>/', views.LightCode.as_view(), name='lightcoder'),
]